# Generated by Django 5.2.2 on 2025-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_ingredient_alter_dish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='dish',
            field=models.ManyToManyField(to='catalog.dish'),
        ),
    ]
