# Generated by Django 5.2.2 on 2025-06-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ingredient_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dish',
            field=models.ManyToManyField(related_name='ingredients', to='catalog.dish'),
        ),
    ]
